// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOci-SJRJZ_0SL2l-Jlhltw7IdcwhrR8o',
    appId: '1:430371579191:web:082f0431c35ed1c69926b2',
    messagingSenderId: '430371579191',
    projectId: 'keep-watch-d3e89',
    authDomain: 'keep-watch-d3e89.firebaseapp.com',
    storageBucket: 'keep-watch-d3e89.firebasestorage.app',
    measurementId: 'G-RM45FQQK0E',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TCzON6iRSL61lMH2SAL5HgPyWJDt6Bc',
    appId: '1:430371579191:android:fef68be2c1dc4e429926b2',
    messagingSenderId: '430371579191',
    projectId: 'keep-watch-d3e89',
    storageBucket: 'keep-watch-d3e89.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAfldygwGyIwlhSdDuE-XYrLLXdqOa3Cw',
    appId: '1:430371579191:ios:1a7f3a808331e8139926b2',
    messagingSenderId: '430371579191',
    projectId: 'keep-watch-d3e89',
    storageBucket: 'keep-watch-d3e89.firebasestorage.app',
    iosBundleId: 'com.example.thesis',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAfldygwGyIwlhSdDuE-XYrLLXdqOa3Cw',
    appId: '1:430371579191:ios:1a7f3a808331e8139926b2',
    messagingSenderId: '430371579191',
    projectId: 'keep-watch-d3e89',
    storageBucket: 'keep-watch-d3e89.firebasestorage.app',
    iosBundleId: 'com.example.thesis',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOci-SJRJZ_0SL2l-Jlhltw7IdcwhrR8o',
    appId: '1:430371579191:web:ce06b45dae951abb9926b2',
    messagingSenderId: '430371579191',
    projectId: 'keep-watch-d3e89',
    authDomain: 'keep-watch-d3e89.firebaseapp.com',
    storageBucket: 'keep-watch-d3e89.firebasestorage.app',
    measurementId: 'G-6Q75M4J7D4',
  );
}
